### ISSUE TITLE
You don't have screenrc

### ISSUE THREAD

**Issue by teamrc** [z1lt0id/.Dotfiles#3]
you need to learn screen.

**Comment by z1lt0id** [comment]
and what is screenrc

On 11 October 2015 21:39:29 GMT+11:00, teamrc <notifications@github.com> wrote:
>you need to learn screen.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/z1lt0id/.Dotfiles/issues/3

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by z1lt0id** [comment]
i looked it uo. i dont really have a need for it.

On 11 October 2015 21:39:29 GMT+11:00, teamrc <notifications@github.com> wrote:
>you need to learn screen.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/z1lt0id/.Dotfiles/issues/3

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
